name: CI Branch 6.0

on:
  push:
    branches:
      - '6.0'
  pull_request:
    branches:
      - '6.0'
  workflow_dispatch:

jobs:
  testsuite:
    name: "Test Suite"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.0.2', '8.1', '8.1' ]
        symfony-version: [ '6.0', '6.1', '6.2', '6.3' ]
    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #extensions: json, libxml, pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, sqlite3
          coverage: pcov

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer update (Symfony version ${{ matrix.symfony-version }})
        run: composer install --prefer-dist --no-interaction

      - name: Run tests
        if: matrix.php-version >= '8.1'
        run: vendor/bin/phpunit --display-deprecations --display-notices --display-warnings --coverage-clover=Tests/coverage.xml

      - name: Run tests
        if: matrix.php-version < '8.1'
        run: vendor/bin/phpunit --verbose --coverage-clover=Tests/coverage.xml

#      - name: Code Coverage Report
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          directory: ./Tests/
#          files: ./Tests/coverage.xml
#          fail_ci_if_error: true
#          verbose: true
